package com.yanzhen.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class LeaveInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.用户id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.leave_date
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd" ,timezone = "GMT+8")
    private Date leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.leave_days
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private Integer leaveDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.reason
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.state
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_info.processInstanceId
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private String processinstanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private static final long serialVersionUID = 1L;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.id
     *
     * @return the value of leave_info.id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.id
     *
     * @param id the value for leave_info.id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.用户id
     *
     * @return the value of leave_info.用户id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.用户id
     *
     * @param userId the value for leave_info.用户id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.leave_date
     *
     * @return the value of leave_info.leave_date
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.leave_date
     *
     * @param leaveDate the value for leave_info.leave_date
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.leave_days
     *
     * @return the value of leave_info.leave_days
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public Integer getLeaveDays() {
        return leaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.leave_days
     *
     * @param leaveDays the value for leave_info.leave_days
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setLeaveDays(Integer leaveDays) {
        this.leaveDays = leaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.reason
     *
     * @return the value of leave_info.reason
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.reason
     *
     * @param reason the value for leave_info.reason
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.state
     *
     * @return the value of leave_info.state
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.state
     *
     * @param state the value for leave_info.state
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_info.processInstanceId
     *
     * @return the value of leave_info.processInstanceId
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public String getProcessinstanceid() {
        return processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_info.processInstanceId
     *
     * @param processinstanceid the value for leave_info.processInstanceId
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setProcessinstanceid(String processinstanceid) {
        this.processinstanceid = processinstanceid == null ? null : processinstanceid.trim();
    }
}