package com.yanzhen.model;

import java.io.Serializable;

public class RoleInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.name
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.remarks
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.id
     *
     * @return the value of role_info.id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.id
     *
     * @param id the value for role_info.id
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.name
     *
     * @return the value of role_info.name
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.name
     *
     * @param name the value for role_info.name
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.remarks
     *
     * @return the value of role_info.remarks
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.remarks
     *
     * @param remarks the value for role_info.remarks
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}