package com.yanzhen.dao;

import com.yanzhen.model.DeptInfo;
import com.yanzhen.model.Node;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("deptDao")
public interface DeptInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int insert(DeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int insertSelective(DeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    DeptInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int updateByPrimaryKeySelective(DeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int updateByPrimaryKey(DeptInfo record);


    /**
     * 高级查询所有的部门信息
     */
    List<DeptInfo> queryDeptAll(DeptInfo info);

    /**
     * 根据父节点id查询记录信息
     */
    List<DeptInfo> queryByFID(@Param("parentId") Integer parentId);

    /**
     * 查询树
     */
    List<Node> queryDeptTree();
}