package com.yanzhen.dao;

import com.yanzhen.model.LeaveInfo;
import com.yanzhen.model.TongJi;
import org.apache.ibatis.annotations.Param;
import org.springframework.security.access.method.P;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("leaveInfoDao")
public interface LeaveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int insert(LeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int insertSelective(LeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    LeaveInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int updateByPrimaryKeySelective(LeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int updateByPrimaryKey(LeaveInfo record);

    /**
     * 获取所有的请假列表信息
     * @param leaveInfo
     * @return
     */
    List<LeaveInfo> queryLeaveAll(LeaveInfo leaveInfo);


    /**
     * 根据流程id获取请假记录信息
     */
    LeaveInfo getLeaveInfoTaskId(@Param("proId") String proId);


    List<TongJi> queryTongjiCounts();
}