package com.yanzhen.dao;

import com.yanzhen.model.User;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

@Component("userDao")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jan 26 21:55:49 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 查询 带条件
     */
    List<User> queryAll(User user);

    /**
     * 登录验证 根据用户名 密码以及角色验证
     */
    User queryUserByUserNameAndPwdAndType(@RequestParam("username") String username,
                                          @RequestParam("password")  String password,
                                          @RequestParam("roleName") String roleName);

    User queryUserInfoByTypeAndRoleAndDeptId(@RequestParam("type") String type,
                                             @RequestParam("role") String role,
                                             @RequestParam("deptId") String deptId);


    //修改密码
    int updatePassword(User user);

}